<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWEWYFHT\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWEWYFHT/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWEWYFHT.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWEWYFHT\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWEWYFHT\App_KernelProdContainer([
    'container.build_hash' => 'WEWYFHT',
    'container.build_id' => '27c73085',
    'container.build_time' => 1768873145,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWEWYFHT');
