<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Product__CLASSMETADATA__' => 0,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Product',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ProductRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'price' => $o[3],
                    'url' => $o[4],
                    'createdAt' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'price' => 'price',
                    'url' => 'url',
                    'created_at' => 'createdAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'price' => 'price',
                    'url' => 'url',
                    'createdAt' => 'created_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'product',
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\Product',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'float',
                'string',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'name',
                'price',
                'url',
                'createdAt',
            ],
            'columnName' => [
                1 => 'id',
                'name',
                'price',
                'url',
                'created_at',
            ],
            'length' => [
                2 => 255,
                4 => 255,
            ],
            'nullable' => [
                4 => true,
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
