<?php

namespace ContainerWEWYFHT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProductControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ApiProductController' shared autowired service.
     *
     * @return \App\Controller\ApiProductController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ApiProductController'] = $instance = new \App\Controller\ApiProductController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\ApiProductController', $container));

        return $instance;
    }
}
