<?php

namespace ContainerL2dEDrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ICCVDbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6ICCVDb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ICCVDb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ApiFavoritesController::favorites' => ['privates', '.service_locator.fX4VlkY.App\\Controller\\ApiFavoritesController::favorites()', 'getApiFavoritesControllerfavoritesService', true],
            'App\\Controller\\ApiFavoritesController::deleteFavorites' => ['privates', '.service_locator.fX4VlkY.App\\Controller\\ApiFavoritesController::deleteFavorites()', 'getApiFavoritesControllerdeleteFavoritesService', true],
            'App\\Controller\\ApiPerfumesController::index' => ['privates', '.service_locator.2KKAeja.App\\Controller\\ApiPerfumesController::index()', 'getApiPerfumesControllerindexService', true],
            'App\\Controller\\ApiPerfumesController::show' => ['privates', '.service_locator.2KKAeja.App\\Controller\\ApiPerfumesController::show()', 'getApiPerfumesControllershowService', true],
            'App\\Controller\\ApiUsersController::index' => ['privates', '.service_locator.j83KHed.App\\Controller\\ApiUsersController::index()', 'getApiUsersControllerindexService', true],
            'App\\Controller\\ApiUsersController::users' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\ApiUsersController::users()', 'getApiUsersControllerusersService', true],
            'App\\Controller\\ApiUsersController::editUser' => ['privates', '.service_locator.j83KHed.App\\Controller\\ApiUsersController::editUser()', 'getApiUsersControllereditUserService', true],
            'App\\Controller\\ApiUsersController::deleteUser' => ['privates', '.service_locator.j83KHed.App\\Controller\\ApiUsersController::deleteUser()', 'getApiUsersControllerdeleteUserService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ApiFavoritesController:favorites' => ['privates', '.service_locator.fX4VlkY.App\\Controller\\ApiFavoritesController::favorites()', 'getApiFavoritesControllerfavoritesService', true],
            'App\\Controller\\ApiFavoritesController:deleteFavorites' => ['privates', '.service_locator.fX4VlkY.App\\Controller\\ApiFavoritesController::deleteFavorites()', 'getApiFavoritesControllerdeleteFavoritesService', true],
            'App\\Controller\\ApiPerfumesController:index' => ['privates', '.service_locator.2KKAeja.App\\Controller\\ApiPerfumesController::index()', 'getApiPerfumesControllerindexService', true],
            'App\\Controller\\ApiPerfumesController:show' => ['privates', '.service_locator.2KKAeja.App\\Controller\\ApiPerfumesController::show()', 'getApiPerfumesControllershowService', true],
            'App\\Controller\\ApiUsersController:index' => ['privates', '.service_locator.j83KHed.App\\Controller\\ApiUsersController::index()', 'getApiUsersControllerindexService', true],
            'App\\Controller\\ApiUsersController:users' => ['privates', '.service_locator.PtMLGj3.App\\Controller\\ApiUsersController::users()', 'getApiUsersControllerusersService', true],
            'App\\Controller\\ApiUsersController:editUser' => ['privates', '.service_locator.j83KHed.App\\Controller\\ApiUsersController::editUser()', 'getApiUsersControllereditUserService', true],
            'App\\Controller\\ApiUsersController:deleteUser' => ['privates', '.service_locator.j83KHed.App\\Controller\\ApiUsersController::deleteUser()', 'getApiUsersControllerdeleteUserService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ApiFavoritesController::favorites' => '?',
            'App\\Controller\\ApiFavoritesController::deleteFavorites' => '?',
            'App\\Controller\\ApiPerfumesController::index' => '?',
            'App\\Controller\\ApiPerfumesController::show' => '?',
            'App\\Controller\\ApiUsersController::index' => '?',
            'App\\Controller\\ApiUsersController::users' => '?',
            'App\\Controller\\ApiUsersController::editUser' => '?',
            'App\\Controller\\ApiUsersController::deleteUser' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ApiFavoritesController:favorites' => '?',
            'App\\Controller\\ApiFavoritesController:deleteFavorites' => '?',
            'App\\Controller\\ApiPerfumesController:index' => '?',
            'App\\Controller\\ApiPerfumesController:show' => '?',
            'App\\Controller\\ApiUsersController:index' => '?',
            'App\\Controller\\ApiUsersController:users' => '?',
            'App\\Controller\\ApiUsersController:editUser' => '?',
            'App\\Controller\\ApiUsersController:deleteUser' => '?',
        ]);
    }
}
