<?php

namespace ContainerL2dEDrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FX4VlkYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fX4VlkY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fX4VlkY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'perfume' => ['privates', '.errored..service_locator.fX4VlkY.App\\Entity\\Perfumes', NULL, 'Cannot autowire service ".service_locator.fX4VlkY": it needs an instance of "App\\Entity\\Perfumes" but this type has been excluded because it\'s a Doctrine entity.'],
            'userService' => ['privates', 'App\\Service\\UserService', 'getUserServiceService', true],
        ], [
            'perfume' => 'App\\Entity\\Perfumes',
            'userService' => 'App\\Service\\UserService',
        ]);
    }
}
