<?php

namespace ContainerL2dEDrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUsersControllereditUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j83KHed.App\Controller\ApiUsersController::editUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j83KHed.App\\Controller\\ApiUsersController::editUser()'] = ($container->privates['.service_locator.j83KHed'] ?? $container->load('get_ServiceLocator_J83KHedService'))->withContext('App\\Controller\\ApiUsersController::editUser()', $container);
    }
}
