<?php

namespace ContainerZOYQsXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q5GA76UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q5GA76U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q5GA76U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'perfumesRepository' => ['privates', 'App\\Repository\\PerfumesRepository', 'getPerfumesRepositoryService', true],
        ], [
            'perfumesRepository' => 'App\\Repository\\PerfumesRepository',
        ]);
    }
}
