<?php

namespace ContainerZOYQsXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YBOcBF0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yBOcBF0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yBOcBF0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'perfumesClubRepository' => ['privates', 'App\\Repository\\PerfumesClubRepository', 'getPerfumesClubRepositoryService', true],
        ], [
            'perfumesClubRepository' => 'App\\Repository\\PerfumesClubRepository',
        ]);
    }
}
