security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: /logout

    access_control:
         - { path: ^/login, roles: PUBLIC_ACCESS }
         - { path: ^/api/perfumes, roles: PUBLIC_ACCESS }
         - { path: ^/api/perfumes/^, roles: PUBLIC_ACCESS }
         - { path: ^/api/favorites, roles: PUBLIC_ACCESS }
         - { path: ^/api/all/users, roles: ROLE_ADMIN }
         - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }