<?php

namespace ContainerT80uTaJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUsersControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6xt1_E9.App\Controller\ApiUsersController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6xt1_E9.App\\Controller\\ApiUsersController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'SaveBdUsers' => ['privates', 'App\\Service\\SaveBdUsers', 'getSaveBdUsersService', true],
        ], [
            'SaveBdUsers' => 'App\\Service\\SaveBdUsers',
        ]))->withContext('App\\Controller\\ApiUsersController::index()', $container);
    }
}
