<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSRMj6Li\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSRMj6Li/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSRMj6Li.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSRMj6Li\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSRMj6Li\App_KernelDevDebugContainer([
    'container.build_hash' => 'SRMj6Li',
    'container.build_id' => '1bf2c2f0',
    'container.build_time' => 1768873620,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSRMj6Li');
