<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIkCfJnt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIkCfJnt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIkCfJnt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIkCfJnt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIkCfJnt\App_KernelDevDebugContainer([
    'container.build_hash' => 'IkCfJnt',
    'container.build_id' => '22717342',
    'container.build_time' => 1780901961,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIkCfJnt');
