<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZbYcqDx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZbYcqDx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZbYcqDx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZbYcqDx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZbYcqDx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZbYcqDx',
    'container.build_id' => '868e1dbb',
    'container.build_time' => 1772761341,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZbYcqDx');
