<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_api_perfumes' => [[], ['_controller' => 'App\\Controller\\ApiPerfumesController::index'], [], [['text', '/api/perfumes']], [], [], []],
    'api_perfumes_detail' => [['id'], ['_controller' => 'App\\Controller\\ApiPerfumesController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/perfumes']], [], [], []],
    'app_api_users' => [[], ['_controller' => 'App\\Controller\\ApiUsersController::index'], [], [['text', '/users']], [], [], []],
    'app_api_favorites' => [[], ['_controller' => 'App\\Controller\\ApiUsersController::favorites'], [], [['text', '/api/favorites']], [], [], []],
    'app_apiusers_headers' => [[], ['_controller' => 'App\\Controller\\ApiUsersController::headers'], [], [['text', '/api/headers']], [], [], []],
    'api_me' => [[], ['_controller' => 'App\\Controller\\ApiUsersController::me'], [], [['text', '/api/me']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\ApiPerfumesController::index' => [[], ['_controller' => 'App\\Controller\\ApiPerfumesController::index'], [], [['text', '/api/perfumes']], [], [], []],
    'App\Controller\ApiPerfumesController::show' => [['id'], ['_controller' => 'App\\Controller\\ApiPerfumesController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/perfumes']], [], [], []],
    'App\Controller\ApiUsersController::index' => [[], ['_controller' => 'App\\Controller\\ApiUsersController::index'], [], [['text', '/users']], [], [], []],
    'App\Controller\ApiUsersController::favorites' => [[], ['_controller' => 'App\\Controller\\ApiUsersController::favorites'], [], [['text', '/api/favorites']], [], [], []],
    'App\Controller\ApiUsersController::headers' => [[], ['_controller' => 'App\\Controller\\ApiUsersController::headers'], [], [['text', '/api/headers']], [], [], []],
    'App\Controller\ApiUsersController::me' => [[], ['_controller' => 'App\\Controller\\ApiUsersController::me'], [], [['text', '/api/me']], [], [], []],
    'App\Controller\AuthController::login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/login']], [], [], []],
];
