<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_products' => [[], ['_controller' => 'App\\Controller\\ApiProductController::listProducts'], [], [['text', '/api/products']], [], [], []],
    'add_product' => [[], ['_controller' => 'App\\Controller\\ProductController::addProduct'], [], [['text', '/add-product']], [], [], []],
    'App\Controller\ApiProductController::listProducts' => [[], ['_controller' => 'App\\Controller\\ApiProductController::listProducts'], [], [['text', '/api/products']], [], [], []],
    'App\Controller\ProductController::addProduct' => [[], ['_controller' => 'App\\Controller\\ProductController::addProduct'], [], [['text', '/add-product']], [], [], []],
];
