<?php

namespace ContainerHvpgDH5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUsersControllerfavoritesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6xt1_E9.App\Controller\ApiUsersController::favorites()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6xt1_E9.App\\Controller\\ApiUsersController::favorites()'] = ($container->privates['.service_locator.6xt1_E9'] ?? $container->load('get_ServiceLocator_6xt1E9Service'))->withContext('App\\Controller\\ApiUsersController::favorites()', $container);
    }
}
