<?php

namespace Container6Gai0Q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W197uAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W19_7uA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W19_7uA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ApiAllPerfumesController::index' => ['privates', '.service_locator.e8I66cD.App\\Controller\\ApiAllPerfumesController::index()', 'getApiAllPerfumesControllerindexService', true],
            'App\\Controller\\ApiBookController::index' => ['privates', '.service_locator.zUpmxTP.App\\Controller\\ApiBookController::index()', 'getApiBookControllerindexService', true],
            'App\\Controller\\ApiBookController::show' => ['privates', '.service_locator.zUpmxTP.App\\Controller\\ApiBookController::show()', 'getApiBookControllershowService', true],
            'App\\Controller\\ApiPerfumeriasController::index' => ['privates', '.service_locator.HwoPxyR.App\\Controller\\ApiPerfumeriasController::index()', 'getApiPerfumeriasControllerindexService', true],
            'App\\Controller\\ApiPerfumeriasController::show' => ['privates', '.service_locator.HwoPxyR.App\\Controller\\ApiPerfumeriasController::show()', 'getApiPerfumeriasControllershowService', true],
            'App\\Controller\\ApiPerfumesClubController::index' => ['privates', '.service_locator.yBOcBF0.App\\Controller\\ApiPerfumesClubController::index()', 'getApiPerfumesClubControllerindexService', true],
            'App\\Controller\\ApiPerfumesClubController::show' => ['privates', '.service_locator.yBOcBF0.App\\Controller\\ApiPerfumesClubController::show()', 'getApiPerfumesClubControllershowService', true],
            'App\\Controller\\ApiProductController::listProducts' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ApiProductController::listProducts()', 'getApiProductControllerlistProductsService', true],
            'App\\Controller\\ProductController::addProduct' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ProductController::addProduct()', 'getProductControlleraddProductService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ApiAllPerfumesController:index' => ['privates', '.service_locator.e8I66cD.App\\Controller\\ApiAllPerfumesController::index()', 'getApiAllPerfumesControllerindexService', true],
            'App\\Controller\\ApiBookController:index' => ['privates', '.service_locator.zUpmxTP.App\\Controller\\ApiBookController::index()', 'getApiBookControllerindexService', true],
            'App\\Controller\\ApiBookController:show' => ['privates', '.service_locator.zUpmxTP.App\\Controller\\ApiBookController::show()', 'getApiBookControllershowService', true],
            'App\\Controller\\ApiPerfumeriasController:index' => ['privates', '.service_locator.HwoPxyR.App\\Controller\\ApiPerfumeriasController::index()', 'getApiPerfumeriasControllerindexService', true],
            'App\\Controller\\ApiPerfumeriasController:show' => ['privates', '.service_locator.HwoPxyR.App\\Controller\\ApiPerfumeriasController::show()', 'getApiPerfumeriasControllershowService', true],
            'App\\Controller\\ApiPerfumesClubController:index' => ['privates', '.service_locator.yBOcBF0.App\\Controller\\ApiPerfumesClubController::index()', 'getApiPerfumesClubControllerindexService', true],
            'App\\Controller\\ApiPerfumesClubController:show' => ['privates', '.service_locator.yBOcBF0.App\\Controller\\ApiPerfumesClubController::show()', 'getApiPerfumesClubControllershowService', true],
            'App\\Controller\\ApiProductController:listProducts' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ApiProductController::listProducts()', 'getApiProductControllerlistProductsService', true],
            'App\\Controller\\ProductController:addProduct' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ProductController::addProduct()', 'getProductControlleraddProductService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ApiAllPerfumesController::index' => '?',
            'App\\Controller\\ApiBookController::index' => '?',
            'App\\Controller\\ApiBookController::show' => '?',
            'App\\Controller\\ApiPerfumeriasController::index' => '?',
            'App\\Controller\\ApiPerfumeriasController::show' => '?',
            'App\\Controller\\ApiPerfumesClubController::index' => '?',
            'App\\Controller\\ApiPerfumesClubController::show' => '?',
            'App\\Controller\\ApiProductController::listProducts' => '?',
            'App\\Controller\\ProductController::addProduct' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ApiAllPerfumesController:index' => '?',
            'App\\Controller\\ApiBookController:index' => '?',
            'App\\Controller\\ApiBookController:show' => '?',
            'App\\Controller\\ApiPerfumeriasController:index' => '?',
            'App\\Controller\\ApiPerfumeriasController:show' => '?',
            'App\\Controller\\ApiPerfumesClubController:index' => '?',
            'App\\Controller\\ApiPerfumesClubController:show' => '?',
            'App\\Controller\\ApiProductController:listProducts' => '?',
            'App\\Controller\\ProductController:addProduct' => '?',
        ]);
    }
}
