<?php

namespace Container6Gai0Q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAllPerfumesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e8I66cD.App\Controller\ApiAllPerfumesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e8I66cD.App\\Controller\\ApiAllPerfumesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'perfumeriasRepository' => ['privates', 'App\\Repository\\PerfumeriasRepository', 'getPerfumeriasRepositoryService', true],
            'perfumesClubRepository' => ['privates', 'App\\Repository\\PerfumesClubRepository', 'getPerfumesClubRepositoryService', true],
        ], [
            'perfumeriasRepository' => 'App\\Repository\\PerfumeriasRepository',
            'perfumesClubRepository' => 'App\\Repository\\PerfumesClubRepository',
        ]))->withContext('App\\Controller\\ApiAllPerfumesController::index()', $container);
    }
}
