<?php

namespace Container6Gai0Q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebugScrapeCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\DebugScrapeCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\DebugScrapeCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:debug-scrape', [], 'Debug: obtiene el HTML de PCComponentes y muestra estructura', false, #[\Closure(name: 'App\\Command\\DebugScrapeCommand')] fn (): \App\Command\DebugScrapeCommand => ($container->privates['App\\Command\\DebugScrapeCommand'] ?? $container->load('getDebugScrapeCommandService')));
    }
}
