<?php

namespace Container6Gai0Q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapePerfumeriasCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapePerfumeriasCommand' shared autowired service.
     *
     * @return \App\Command\ScrapePerfumeriasCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapePerfumeriasCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PerfumeriasScraper.php';

        $container->privates['App\\Command\\ScrapePerfumeriasCommand'] = $instance = new \App\Command\ScrapePerfumeriasCommand(new \App\Service\PerfumeriasScraper(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\PCComponentRepository'] ?? $container->load('getPCComponentRepositoryService'))));

        $instance->setName('app:scrape-perfumerias');
        $instance->setDescription('Scrapea perfumes y los guarda en la base de datos');

        return $instance;
    }
}
