<?php

namespace Container6Gai0Q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapePCFactoryCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapePCFactoryCommand' shared autowired service.
     *
     * @return \App\Command\ScrapePCFactoryCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapePCFactoryCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PCFactoryScraper.php';

        $container->privates['App\\Command\\ScrapePCFactoryCommand'] = $instance = new \App\Command\ScrapePCFactoryCommand(new \App\Service\PCFactoryScraper(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\PCFactoryComponentRepository'] ?? $container->load('getPCFactoryComponentRepositoryService'))));

        $instance->setName('app:scrape-pcfactory');
        $instance->setDescription('Scrapea componentes de PC Factory y los guarda en la base de datos');

        return $instance;
    }
}
