<?php

namespace Container6Gai0Q2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeProductsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapeProductsCommand' shared autowired service.
     *
     * @return \App\Command\ScrapeProductsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapeProductsCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ProductScraper.php';

        $container->privates['App\\Command\\ScrapeProductsCommand'] = $instance = new \App\Command\ScrapeProductsCommand(new \App\Service\ProductScraper(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))));

        $instance->setName('app:scrape-products');
        $instance->setDescription('Scrapea libros y los guarda en la base de datos');

        return $instance;
    }
}
