<?php

namespace Container8RM0k4n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiBookControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApiBookController' shared autowired service.
     *
     * @return \App\Controller\ApiBookController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ApiBookController.php';

        $container->services['App\\Controller\\ApiBookController'] = $instance = new \App\Controller\ApiBookController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\ApiBookController', $container));

        return $instance;
    }
}
