<?php

namespace Container8RM0k4n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapePCComponentsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapePCComponentsCommand' shared autowired service.
     *
     * @return \App\Command\ScrapePCComponentsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapePCComponentsCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PCComponentScraper.php';

        $container->privates['App\\Command\\ScrapePCComponentsCommand'] = $instance = new \App\Command\ScrapePCComponentsCommand(new \App\Service\PCComponentScraper(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\PCComponentRepository'] ?? $container->load('getPCComponentRepositoryService'))));

        $instance->setName('app:scrape-pccomponents');
        $instance->setDescription('Scrapea componentes de PCComponentes y los guarda en la base de datos');

        return $instance;
    }
}
