<?php

namespace Container8RM0k4n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapePCFactoryCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ScrapePCFactoryCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ScrapePCFactoryCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:scrape-pcfactory', [], 'Scrapea componentes de PC Factory y los guarda en la base de datos', false, #[\Closure(name: 'App\\Command\\ScrapePCFactoryCommand')] fn (): \App\Command\ScrapePCFactoryCommand => ($container->privates['App\\Command\\ScrapePCFactoryCommand'] ?? $container->load('getScrapePCFactoryCommandService')));
    }
}
