<?php

namespace Container8RM0k4n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapeBooksCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapeBooksCommand' shared autowired service.
     *
     * @return \App\Command\ScrapeBooksCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapeBooksCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/BookScraper.php';

        $container->privates['App\\Command\\ScrapeBooksCommand'] = $instance = new \App\Command\ScrapeBooksCommand(new \App\Service\BookScraper(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))));

        $instance->setName('app:scrape-books');
        $instance->setDescription('Scrapea libros y los guarda en la base de datos');

        return $instance;
    }
}
