<?php

namespace ContainerN3txqf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2KKAejaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2KKAeja' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2KKAeja'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'perfumesRepository' => ['privates', 'App\\Repository\\PerfumesRepository', 'getPerfumesRepositoryService', true],
            'precioContenidoRepository' => ['privates', 'App\\Repository\\PrecioContenidoRepository', 'getPrecioContenidoRepositoryService', true],
        ], [
            'perfumesRepository' => 'App\\Repository\\PerfumesRepository',
            'precioContenidoRepository' => 'App\\Repository\\PrecioContenidoRepository',
        ]);
    }
}
