<?php

namespace ContainerN3txqf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiFavoritesControllerdeleteFavoritesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fX4VlkY.App\Controller\ApiFavoritesController::deleteFavorites()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fX4VlkY.App\\Controller\\ApiFavoritesController::deleteFavorites()'] = ($container->privates['.service_locator.fX4VlkY'] ?? $container->load('get_ServiceLocator_FX4VlkYService'))->withContext('App\\Controller\\ApiFavoritesController::deleteFavorites()', $container);
    }
}
