<?php

namespace ContainerN3txqf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerfumesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fX4VlkY.App\Entity\Perfumes' shared service.
     *
     * @return \App\Entity\Perfumes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fX4VlkY": it needs an instance of "App\\Entity\\Perfumes" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
