<?php

namespace ContainerJox322b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPerfumesControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q5GA76U.App\Controller\ApiPerfumesController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q5GA76U.App\\Controller\\ApiPerfumesController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'perfumesRepository' => ['privates', 'App\\Repository\\PerfumesRepository', 'getPerfumesRepositoryService', true],
        ], [
            'perfumesRepository' => 'App\\Repository\\PerfumesRepository',
        ]))->withContext('App\\Controller\\ApiPerfumesController::show()', $container);
    }
}
