<?php

namespace ContainerKgOGJbB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiBookControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zUpmxTP.App\Controller\ApiBookController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zUpmxTP.App\\Controller\\ApiBookController::index()'] = ($container->privates['.service_locator.zUpmxTP'] ?? $container->load('get_ServiceLocator_ZUpmxTPService'))->withContext('App\\Controller\\ApiBookController::index()', $container);
    }
}
