<?php

namespace ContainerKgOGJbB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapePerfumesClubCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapePerfumesClubCommand' shared autowired service.
     *
     * @return \App\Command\ScrapePerfumesClubCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapePerfumesClubCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PerfumesClubScraper.php';

        $container->privates['App\\Command\\ScrapePerfumesClubCommand'] = $instance = new \App\Command\ScrapePerfumesClubCommand(new \App\Service\PerfumesClubScraper(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\PCComponentRepository'] ?? $container->load('getPCComponentRepositoryService'))));

        $instance->setName('app:scrape-perfumes-club');
        $instance->setDescription('Scrapea perfumes y los guarda en la base de datos');

        return $instance;
    }
}
