<?php

namespace ContainerKgOGJbB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapePerfumesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapePerfumesCommand' shared autowired service.
     *
     * @return \App\Command\ScrapePerfumesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapePerfumesCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PerfumesScraper.php';

        $container->privates['App\\Command\\ScrapePerfumesCommand'] = $instance = new \App\Command\ScrapePerfumesCommand(new \App\Service\PerfumesScraper(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\StoresRepository'] ?? $container->load('getStoresRepositoryService'))));

        $instance->setName('app:scrape-perfumes-new');
        $instance->setDescription('Scrapea perfumes y los guarda en la base de datos');

        return $instance;
    }
}
