<?php

namespace ContainerKgOGJbB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapePerfumeriasCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ScrapePerfumeriasCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ScrapePerfumeriasCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:scrape-perfumerias', [], 'Scrapea perfumes y los guarda en la base de datos', false, #[\Closure(name: 'App\\Command\\ScrapePerfumeriasCommand')] fn (): \App\Command\ScrapePerfumeriasCommand => ($container->privates['App\\Command\\ScrapePerfumeriasCommand'] ?? $container->load('getScrapePerfumeriasCommandService')));
    }
}
