<?php

namespace ContainerYVeJ4x7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPerfumesClubControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yBOcBF0.App\Controller\ApiPerfumesClubController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yBOcBF0.App\\Controller\\ApiPerfumesClubController::index()'] = ($container->privates['.service_locator.yBOcBF0'] ?? $container->load('get_ServiceLocator_YBOcBF0Service'))->withContext('App\\Controller\\ApiPerfumesClubController::index()', $container);
    }
}
