<?php

namespace ContainerYVeJ4x7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPerfumeriasControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HwoPxyR.App\Controller\ApiPerfumeriasController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HwoPxyR.App\\Controller\\ApiPerfumeriasController::show()'] = ($container->privates['.service_locator.HwoPxyR'] ?? $container->load('get_ServiceLocator_HwoPxyRService'))->withContext('App\\Controller\\ApiPerfumeriasController::show()', $container);
    }
}
