<?php

namespace ContainerYVeJ4x7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebugScrapeCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DebugScrapeCommand' shared autowired service.
     *
     * @return \App\Command\DebugScrapeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/DebugScrapeCommand.php';

        $container->privates['App\\Command\\DebugScrapeCommand'] = $instance = new \App\Command\DebugScrapeCommand(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));

        $instance->setName('app:debug-scrape');
        $instance->setDescription('Debug: obtiene el HTML de PCComponentes y muestra estructura');

        return $instance;
    }
}
