<?php

namespace ContainerYVeJ4x7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapePerfumesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapePerfumesCommand' shared autowired service.
     *
     * @return \App\Command\ScrapePerfumesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapePerfumesCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PerfumesScraperService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SaveBdPerfumes.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PeticionesUrlsService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/NodosPerfumerias.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FormatterService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/NodosPerfumeriaClub.php';

        $a = ($container->privates['App\\Repository\\StoresRepository'] ?? $container->load('getStoresRepositoryService'));
        $b = new \App\Service\FormatterService();

        $container->privates['App\\Command\\ScrapePerfumesCommand'] = $instance = new \App\Command\ScrapePerfumesCommand(new \App\Service\PerfumesScraperService(new \App\Service\SaveBdPerfumes(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))), new \App\Service\PeticionesUrlsService(), new \App\Service\NodosPerfumerias($a, $b), new \App\Service\NodosPerfumeriaClub($a, $b)));

        $instance->setName('app:scrape-perfumes');
        $instance->setDescription('Scrapea perfumes y los guarda en la base de datos');

        return $instance;
    }
}
