<?php

namespace ContainerYVeJ4x7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapePCComponentsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ScrapePCComponentsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ScrapePCComponentsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:scrape-pccomponents', [], 'Scrapea componentes de PCComponentes y los guarda en la base de datos', false, #[\Closure(name: 'App\\Command\\ScrapePCComponentsCommand')] fn (): \App\Command\ScrapePCComponentsCommand => ($container->privates['App\\Command\\ScrapePCComponentsCommand'] ?? $container->load('getScrapePCComponentsCommandService')));
    }
}
